### ISSUE TITLE
webview_flutter 0.3.4 Flutter: Web view application only a particular website(main url) run in the application, others open in local browser of phone 

### ISSUE THREAD

**Issue by amankataria** [fluttercommunity/flutter_webview_plugin#347]
I have a web view application in Flutter. The plugin/package is "flutter_webview_plugin". In Webview Scaffold, I have url= 'www.google.com'. Now I want that any URL which doesn't contain "google.com" opens in the local browser of the phone.

Maybe if I can restrict the Web view plugin if URL doesn't contain "google.com"

Please let me know how can I achieve this.

Here is my code:

```
 WebviewScaffold(
    url: "http://www.google.com")
```
Further Clarification: I have a web view application. So the website that I have, has a lot of links in it. I don't want links other than my domain links to load in webview app. I want it to open externally.

**Link to issue first reported:** https://stackoverflow.com/questions/55125577/flutter-web-view-application-only-a-particular-website-run-in-the-application

**Comment by hnvn** [comment]
Check my fork: https://github.com/hnvn/flutter_webview_plugin, use `invalidUrlRegex` to restrict your working urls

**Comment by amankataria** [comment]
@hnvn How exactly can I implement this in my project?
I apologize, I am new to all this, so its difficult to get it.

**Comment by charafau** [comment]
@hnvn  is this your PR which is fixing this? https://github.com/fluttercommunity/flutter_webview_plugin/pull/292  I would like to merge it, but could you please rebase with master ?

**Comment by hnvn** [comment]
Done

**Comment by charafau** [comment]
Thank you, I will test it today and merge if it's alright.

**Comment by amankataria** [comment]
@charafau is the feature added in the main package? I am still not exactly sure how can I implement this in my app?

**Comment by AlejandroC90** [comment]
> @charafau is the feature added in the main package? I am still not exactly sure how can I implement this in my app.

Did you solved this?

**Comment by charafau** [comment]
@amankataria @AlejandroC90  yes it's part of main package (in 0.3.2)

PRs was only for restricting urls to be loaded. Write your regex and and check if your url is validated, when open webview (with restriction so user wont redirect to custom domains) otherwise open browser with url_launcher plugin
