### ISSUE TITLE
build ios  warning: incompatible pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from 'id _Nullable'

### ISSUE THREAD

**Issue by sm9i** [fluttercommunity/flutter_webview_plugin#409]
` /Users/furun/.pub-cache/hosted/pub.flutter-io.cn/flutter_webview_plugin-0.3.4/ios/Classes/FlutterWebviewPlugin.m:83:22: warning: incompatible pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from 'id _Nullable'
    [-Wint-conversion]
        _enableAppScheme = call.arguments[@"enableAppScheme"];
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/furun/.pub-cache/hosted/pub.flutter-io.cn/flutter_webview_plugin-0.3.4/ios/Classes/FlutterWebviewPlugin.m:252:24: warning: comparison of distinct pointer types ('NSString *' and 'NSNull * _Nonnull') [-Wcompare-distinct-pointer-types]
      if (_invalidUrlRegex != [NSNull null] && urlString != nil) {
          ~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~
    /Users/furun/.pub-cache/hosted/pub.flutter-io.cn/flutter_webview_plugin-0.3.4/ios/Classes/FlutterWebviewPlugin.m:318:94: warning: values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead
    [-Wformat]
        [channel invokeMethod:@"onError" arguments:@{@"code": [NSString stringWithFormat:@"%ld", error.code], @"error": error.localizedDescription}];
                                                                                           ~~~   ^~~~~~~~~~
                                                                                           %ld   (long)
`

**Comment by sm9i** [comment]
sorry,Somewhat chaotic

**Comment by anysunflower** [comment]
meet the issue too，already set info.plist

**Comment by anysunflower** [comment]
flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[!] Android Studio (not installed)
[✓] Connected device (1 available)
```


info.plist already set

Xcode target: iOS 10   

my build report


```
Xcode's output:
↳
    /Users/Geek/work/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.10+1/ios/Classes/FlutterWebviewPlugin.m:92:22: warning: incompatible pointer to integer conversion assigning to
    'BOOL' (aka 'signed char') from 'id _Nullable' [-Wint-conversion]
        _enableAppScheme = call.arguments[@"enableAppScheme"];
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/Geek/work/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.10+1/ios/Classes/FlutterWebviewPlugin.m:434:98: warning: values of type 'NSInteger' should not be used as format
    arguments; add an explicit cast to 'long' instead [-Wformat]
        [channel invokeMethod:@"onHttpError" arguments:@{@"code": [NSString stringWithFormat:@"%ld", error.code], @"url": url}];
                                                                                               ~~~   ^~~~~~~~~~
                                                                                               %ld   (long)
    /Users/Geek/work/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.10+1/ios/Classes/FlutterWebviewPlugin.m:442:98: warning: values of type 'NSInteger' should not be used as format
    arguments; add an explicit cast to 'long' instead [-Wformat]
        [channel invokeMethod:@"onHttpError" arguments:@{@"code": [NSString stringWithFormat:@"%ld", error.code], @"error": error.localizedDescription}];
                                                                                               ~~~   ^~~~~~~~~~
                                                                                               %ld   (long)
    /Users/Geek/work/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.10+1/ios/Classes/FlutterWebviewPlugin.m:450:106: warning: values of type 'NSInteger' should not be used as format
    arguments; add an explicit cast to 'long' instead [-Wformat]
                [channel invokeMethod:@"onHttpError" arguments:@{@"code": [NSString stringWithFormat:@"%ld", response.statusCode], @"url": webView.URL.absoluteString}];
                                                                                                       ~~~   ^~~~~~~~~~~~~~~~~~~
                                                                                                       %ld   (long)
```

**Comment by rfitz123** [comment]
Same issue, but with `FLTFirebaseAuthPlugin`. Any fixes?

**Comment by anysunflower** [comment]
> Same issue, but with `FLTFirebaseAuthPlugin`. Any fixes?

I fixed all the error by following steps,you can have a try

[reference](https://github.com/Baseflow/flutter-permission-handler/issues/191#issuecomment-575022497)

**Comment by awhitford** [comment]
I am using **flutter_webview_plugin 0.3.11** with **Flutter 1.17** and still see **4 warnings generated**:
```
    /Users/anthony/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.11/ios/Classes/FlutterWebviewPlugin.m:92:22:
    warning: incompatible pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from 'id _Nullable' [-Wint-conversion]
        _enableAppScheme = call.arguments[@"enableAppScheme"];
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/anthony/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.11/ios/Classes/FlutterWebviewPlugin.m:434:98:
    warning: values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
        [channel invokeMethod:@"onHttpError" arguments:@{@"code": [NSString stringWithFormat:@"%ld", error.code], @"url": url}];
                                                                                               ~~~   ^~~~~~~~~~
                                                                                               %ld   (long)
    /Users/anthony/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.11/ios/Classes/FlutterWebviewPlugin.m:442:98:
    warning: values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
        [channel invokeMethod:@"onHttpError" arguments:@{@"code": [NSString stringWithFormat:@"%ld", error.code], @"error":
        error.localizedDescription}];
                                                                                               ~~~   ^~~~~~~~~~
                                                                                               %ld   (long)
    /Users/anthony/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.11/ios/Classes/FlutterWebviewPlugin.m:450:106:
    warning: values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
                [channel invokeMethod:@"onHttpError" arguments:@{@"code": [NSString stringWithFormat:@"%ld", response.statusCode], @"url":
                webView.URL.absoluteString}];
                                                                                                       ~~~   ^~~~~~~~~~~~~~~~~~~
                                                                                                       %ld   (long)
    4 warnings generated.
```

**Comment by demsey2** [comment]
any update on this one will be appreciated

**Comment by gururaja-kambala** [comment]
same issue here, any update?
